
name: make and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache lib
      uses: actions/cache@v2
      with:
        path: lib
        key: ${{ runner.os }}-lib

    - name: install prerequisites
      run: sudo apt update && sudo apt install mpi-default-dev flex libscotch-dev
    - name: make distclean
      run: make distclean # echo not running "make distclean" -> using "Cache lib"
    - name: make
      run: make -j
    - name: test
      run: echo TODO make test not added yet
